name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize, ready_for_review]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    if: '! github.event.pull_request.draft'
    steps:
      - run: echo 'foo'


      - uses: sgpublic/delete-release-action@v1.1
        with:
          release-drop: false
          pre-release-drop: true
          pre-release-drop-tag: true
          pre-release-keep-count: -1
          draft-drop-count: -1
          draft-drop: true
        env:
          GITHUB_TOKEN: ${{ github.token }}
      
