name: 📖 Generate Release


on:
  workflow_run:
    workflows: [CI]
    types:
      - completed


jobs:
  generate-release:
    uses: stetind/stem-reusable-workflows/.github/workflows/generate-release.yaml@feat/gs/automate-release
