name: 📖 Generate Release


on:
  workflow_run:
    workflows: [CI]
    types:
      - completed


jobs:
  generate-release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: stetind/stem-reusable-workflows/.github/workflows/generate-release.yaml@ref/gs/delete-old-releases
