name: 📖 Generate Release


on:
  workflow_run:
    workflows: [CI]
    types:
      - completed


jobs:
  generate-release:
   # if: ${{ github.ref == 'refs/heads/main' }} #I will only run on the main branch and not on pull request
    uses: stetind/stem-reusable-workflows/.github/workflows/make-release.yaml@feat/gs/automate-release
