name: 📖 Generate Release


on:
  pull_request:
    types: [ converted_to_draft ]
  workflow_run:
    workflows: [CI]
    types:
      - completed


jobs:
  generate-release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: stetind/stem-reusable-workflows/.github/workflows/generate-release.yaml@main
