name: PR Labeler

on:
  pull_request:
    types: [opened, closed, reopened]

jobs:
  pr-labeler:
    runs-on: ubuntu-latest
    steps:
      - name: Auto-label issue
        uses: TimonVS/pr-labeler-action@v4
        with:
          repo-token: ${{ github.token }}
          configuration-path: stetind/stem-reusable-workflows/.github/workflows/pr-labeler.yaml@feat/vs/autolabel-prs
