name: PR Labeler
on:
  workflow_call:
    secrets:
      repo_token:
        required: true

jobs:
  pr-labeler:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: 'Auto-label issue'
        uses: TimonVS/pr-labeler-action@v4
        with:
          repo-token: ${{ secrets.repo_token }}
          configuration-path: .github/pr-labeler.yml
