name: Pull Request Labeler
on:
  pull_request:
    types: [opened, closed, reopened]

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Auto-label issue
        uses: actions/labeler@v5
        with:
          configuration-path: stetind/stem-reusable-workflows/.github/pr-labeler.yml@feat/vs/autolabel-prs
