name: PR Labeler
on:
  pull_request:
    types: [opened, closed, reopened]
  workflow_dispatch:

jobs:
  pr-labeler:
    uses: stetind/stem-reusable-workflows/.github/workflows/pr-labeler.yaml@feat/vs/autolabel-prs
