name: 📖 Generate Release

on:
  workflow_run:
    workflows: [CI]
    types:
      - completed
    branches:
      - main

jobs:
  generate-release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: stetind/stem-reusable-workflows/.github/workflows/generate-release.yaml@gs/test-auto-release
